import{a as L,S as w,i}from"./assets/vendor-DJ02cXU5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="52509329-ddcf2edcf50d80102bc7df96b",q="https://pixabay.com/api/";async function m(n,t=1){try{return(await L.get(q,{params:{key:S,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(a){throw new Error(a.message)}}let d;function f(n){const t=document.querySelector(".gallery"),a=n.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p>Likes ${o.likes}</p>
          <p>Views ${o.views}</p>
          <p>Comments ${o.comments}</p>
          <p>Downloads ${o.downloads}</p>
        </div>
      </li>`).join("");t.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new w(".gallery a")}function b(){document.querySelector(".gallery").innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}function v(){document.querySelector(".load-more").classList.remove("hidden")}function p(){document.querySelector(".load-more").classList.add("hidden")}const g=document.querySelector(".form"),E=g.querySelector("input[name='search-text']"),P=document.querySelector(".load-more");let l="",s=1,u=0;g.addEventListener("submit",async n=>{if(n.preventDefault(),l=E.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}s=1,b(),p(),y();try{const t=await m(l,s);if(u=t.totalHits,!t.hits.length){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t.hits),t.hits.length<u&&v()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});P.addEventListener("click",async()=>{s+=1,y();try{const n=await m(l,s);f(n.hits);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),s*15>=u&&(p(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
